### ISSUE TITLE
The call to http://api.marcos.do/rates is raising HTTP 500 error

### ISSUE THREAD

**Issue by aterronb** [MaG21/curry#12]
As subject.

TIA

**Comment by MaG21** [comment]
Hello, my apologizes for the late response.

Thank you once again for reporting this issue.

Unfortunately I'm unable to fix the service http://api.marcos.do, because I no longer control it. 

What does this mean? It means that I'll keep maintaining this repository and fix any issue people report, but I won't be able to upload changes to api.marcos.do.

**Comment by eneldoserrata** [comment]
@aterronb the service already update now you can try it!
http://api.marcos.do/rates
