### ISSUE TITLE
/central_bank_rates not working (reason)

### ISSUE THREAD

**Issue by evaldez89** [MaG21/curry#15]
https://github.com/MaG21/curry/blob/646d41d0643457e6606cf71c89b9cf7cc7317427/scraper.rb#L174

The end point to obtain the central bank rates is not longer working.

Reason: 
The url is not longer available:
`DATA_URI         = URI('https://www.bancentral.gov.do/tasas_cambio/TASA_DOLAR_REFERENCIA_MC.XLS')`
[https://www.bancentral.gov.do/tasas_cambio/TASA_DOLAR_REFERENCIA_MC.XLS](https://www.bancentral.gov.do/tasas_cambio/TASA_DOLAR_REFERENCIA_MC.XLS)

What would be a workaround to make this posible again?

**Comment by MaG21** [comment]
We were doing OCR in the past, but it wasn't as reliable as downloading and parsing a spreadsheet.

If I remember well, they (the central bank) had some issues 1 or 2 weeks ago (I think). Maybe because they use Microsoft Azure [Read more here](https://www.datacenterdynamics.com/news/microsoft-azure-suffers-outage-after-cooling-issue/), who knows.

Anyways after digging a little I found the new URL for the spreadsheet we use. 

I'll be fixing this issue ASAP,

Thanks for letting me know.

PS: I know I haven't live up to my promises, but I WILL refactor this project and later on (not so far in the future), host it in my own servers)
