### ISSUE TITLE
Add Banco BHD Leon to the list

### ISSUE THREAD

**Issue by aterronb** [MaG21/curry#6]
This bank also publish the USD and Euro rates in the web page. Would be a good addition to the api.

**Comment by MaG21** [comment]
Done.

**Comment by MaG21** [comment]
Changes are only visible on branch `v2.0`, however BHD Leon rates won't be available on master till v2.0 is usable, my apologies in advance.

But not all is lost, if you really need this feature, you can go ahead and use `v2.0` since all tests are passing.

Please don't hesitate to create another issue for any feature or bug you may encounter.

Thanks

**Comment by aterronb** [comment]
Thanks. I use the service via API (api.marcos.do). Any idea when will it be available with the API?

**Comment by MaG21** [comment]
I don't know.

Maybe tonight I might be able to push some of these changes into production. If not, changes will be available at the end of the week.

**Comment by aterronb** [comment]
Ok. Thank you.

**Comment by MaG21** [comment]
BHD Leon rates are now visible on http://api.marcos.do/rates

**Comment by aterronb** [comment]
Muchas gracias.
